#实体管理
EntityManager:
  #清理限制 (-1 关闭)
  Limit:
    #低于 min 值不会执行任何清理任务
    min: 400
    #大于 max 值立即进行清理 (Mod服不建议开启)
    max: 4000

  #实体固定清理周期 (秒)
  Time: 3600

  #公共垃圾箱
  Bin:
    enable: true
    page: 4

  ##清理提示
  Message:
    #开启 Boss 血条倒计时
    bossBar: true
    #每次发送 before 的时间
    time:
      - 60
      - 30
      - 15
      - 5

  #清理命名实体 (仅对原版生效）
  Rename: true

  #清理规则
  Rules:
    #模组实体不按照 animals与monster清理 （推荐）
    mode: true
    #白名单
    whitelist:
      #动物
      - "animals"
    #黑名单
    blacklist:
      #怪物
      - "monster"

    #掉落物
    item:
      #清理掉落物
      enable: true
      #quick-shop:    不清理QuickShop悬浮物(仅测试1.19.2)
        #lore: '"shopLocation":"Location{'

      #钻石镐:                     #节点名(随意)
        #id: "minecraft:diamond_pickaxe"   #物品id
        #name: "钻石制成"                   #物品名
        #lore: "不被清理"                   #描述
        #name/lore 开头为*则开启模糊匹配 如： name: "*不被清理"

    #针对某个世界单独进行规则处理
    custom:
      #world:       #世界名
        #whitelist: #白名单
        #blacklist: #黑名单
        #item:      #掉落物
          #开启掉落物清理
          #enable: true

  #更新检测 有新版本时会在控制台提示
  Update: true
  #开启防止玩家踩踏农作物
  enablePlayerFarmProtect: true
  #开启防止实体踩踏农作物
  enableEntityFarmProtect: true
  #开启防止踩踏作物的世界
  farm-protect-worlds:
    - "world"