name: ClearEntity
version: '${project.version}'
main: cn.konfan.clearentity.ClearEntity
api-version: 1.13
commands:
  ClearEntity:
    aliases:
      - ce
    description: "/ClearEntity help  - Show Commands"
permissions:
  clearentity.admin:
    default: op
    description: "use /ClearEntity [list/search/clear/reload]"
  clearentity.open:
    default: not op
    description: "/ClearEntity open"
